# Generated by Django 4.0.5 on 2022-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_activation_code_user_login_user_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
