# Generated by Django 4.0.5 on 2022-06-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/home/uluk/Desktop/my_project/first_project/media/default/default_author.png', null=True, upload_to='users'),
        ),
    ]
