# Generated by Django 4.0.5 on 2022-06-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='../media/default/default_author.png', null=True, upload_to='users'),
        ),
    ]
